default: &default
  additional_paths:
  - /Users/qinmingyuan/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activestorage-6.1.3.2/app/assets/javascripts
  - /Users/qinmingyuan/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actioncable-6.1.3.2/app/assets/javascripts
  - /Users/qinmingyuan/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actionmailbox-6.1.3.2/app/views
  - /Users/qinmingyuan/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actiontext-6.1.3.2/app/views
  - /Users/qinmingyuan/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/kaminari-core-1.2.1/app/views
  - /Users/qinmingyuan/work/ruby/default_form/app/packs/entrypoints
  - /Users/qinmingyuan/work/engine/rails_ui/app/assets/images
  - /Users/qinmingyuan/work/engine/rails_ui/app/assets/javascript
  - /Users/qinmingyuan/work/engine/rails_ui/app/assets/stylesheets
  - /Users/qinmingyuan/work/engine/rails_ui/app/views
  - /Users/qinmingyuan/work/engine/rails_com/app/packs/images
  - /Users/qinmingyuan/work/engine/rails_com/app/views
  - /Users/qinmingyuan/work/engine/rails_org/app/views
  - /Users/qinmingyuan/work/engine/rails_auth/app/views
  - /Users/qinmingyuan/work/engine/rails_data/app/views
  - /Users/qinmingyuan/work/engine/rails_quip/app/views
  - /Users/qinmingyuan/work/engine/rails_role/app/views
  - /Users/qinmingyuan/work/engine/rails_ship/app/views
  - /Users/qinmingyuan/work/engine/rails_audit/app/views
  - /Users/qinmingyuan/work/engine/rails_bench/app/views
  - /Users/qinmingyuan/work/engine/rails_email/app/views
  - /Users/qinmingyuan/work/engine/rails_event/app/views
  - /Users/qinmingyuan/work/engine/rails_trade/app/views
  - /Users/qinmingyuan/work/engine/rails_agency/app/views
  - /Users/qinmingyuan/work/engine/rails_attend/app/views
  - /Users/qinmingyuan/work/engine/rails_detail/app/views
  - /Users/qinmingyuan/work/engine/rails_growth/app/views
  - /Users/qinmingyuan/work/engine/rails_notice/app/packs/entrypoints
  - /Users/qinmingyuan/work/engine/rails_notice/app/views
  - /Users/qinmingyuan/work/engine/rails_wechat/app/views
  - /Users/qinmingyuan/work/engine/rails_factory/app/views
  - /Users/qinmingyuan/work/engine/rails_finance/app/views
  - /Users/qinmingyuan/work/engine/rails_profile/app/views
  - /Users/qinmingyuan/work/engine/rails_interact/app/views
  - /Users/qinmingyuan/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/turbo-rails-0.5.9/app/assets/javascripts
  engine_paths:
  - /Users/qinmingyuan/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actionmailbox-6.1.3.2/app/views
  - /Users/qinmingyuan/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actiontext-6.1.3.2/app/views
  - /Users/qinmingyuan/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/kaminari-core-1.2.1/app/views
  - /Users/qinmingyuan/work/engine/rails_ui/app/views
  - /Users/qinmingyuan/work/engine/rails_com/app/views
  - /Users/qinmingyuan/work/engine/rails_org/app/views
  - /Users/qinmingyuan/work/engine/rails_auth/app/views
  - /Users/qinmingyuan/work/engine/rails_data/app/views
  - /Users/qinmingyuan/work/engine/rails_quip/app/views
  - /Users/qinmingyuan/work/engine/rails_role/app/views
  - /Users/qinmingyuan/work/engine/rails_ship/app/views
  - /Users/qinmingyuan/work/engine/rails_audit/app/views
  - /Users/qinmingyuan/work/engine/rails_bench/app/views
  - /Users/qinmingyuan/work/engine/rails_email/app/views
  - /Users/qinmingyuan/work/engine/rails_event/app/views
  - /Users/qinmingyuan/work/engine/rails_trade/app/views
  - /Users/qinmingyuan/work/engine/rails_agency/app/views
  - /Users/qinmingyuan/work/engine/rails_attend/app/views
  - /Users/qinmingyuan/work/engine/rails_detail/app/views
  - /Users/qinmingyuan/work/engine/rails_growth/app/views
  - /Users/qinmingyuan/work/engine/rails_notice/app/views
  - /Users/qinmingyuan/work/engine/rails_wechat/app/views
  - /Users/qinmingyuan/work/engine/rails_factory/app/views
  - /Users/qinmingyuan/work/engine/rails_finance/app/views
  - /Users/qinmingyuan/work/engine/rails_profile/app/views
  - /Users/qinmingyuan/work/engine/rails_interact/app/views
development:
  <<: *default
  public_output_path: packs-dev
  dev_server:
    disableHostCheck: true
    headers:
      Access-Control-Allow-Headers: x-csrf-token, x-requested-with
test:
  <<: *default
  public_output_path: packs-test
staging:
  <<: *default
  compile: false
  cache_manifest: true
production:
  <<: *default
  compile: false
